### ISSUE TITLE
OCSP stapling in AWS (with CloudFront)

### ISSUE THREAD

**Issue by thinrope** [18F/https#40]
I have been digging the web on how to do OCSP stapling inside AWS and was initially discouraged by your documentation (in https/configuration/elb.md ) that it doesn't work on ELB. While I think it is accurate, apparently using the CloudFront CDN, it is possible to properly implement it:

https://aws.amazon.com/blogs/aws/cloudfront-ssl-ciphers-session-ocsp-pfs/
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-ocsp-stapling

You may consider updating that documentation, if relevant to your organisation (sorry I am not very clear what is the repo purpose, so feel free to ignore).

**Comment by konklone** [comment]
We've removed that file from this repo, and don't maintain documentation on ELBs and OCSP stapling anymore. If you can find a current document in the repo, or a page we have hosted somewhere, that has inaccurate information, definitely link us to it so we can fix it. 

And thanks for pointing all this information out -- OCSP stapling is an important privacy and security measure that we'd like to have in place.
